### ISSUE TITLE
lidar的作用

### ISSUE THREAD

**Issue by Tangme10** [ThomasVonWu/SparseEnd2End#10]
大佬您好，我在config中看到有雷达的接口
'''
train_pipeline = [
    dict(type="LoadMultiViewImageFromFiles", to_float32=True),
    dict(
        type="LoadPointsFromFile",
        coord_type="LIDAR",
        load_dim=5,
        use_dim=5,
        file_client_args=file_client_args,
    ),
'''
'''
input_modality = dict(
    use_lidar=False,
    use_camera=True,
    use_radar=False,
    use_map=False,
    use_external=False,
)
'''
请问只是为了引入点云为深度估计做辅助训练任务吗，还有其他的作用吗

**Comment by ThomasVonWu** [comment]
- 辅助监督训练分支,类似BEVDepthNet, 只在训练过程使用,推理数据流不走这个分支.
