### ISSUE TITLE
有关于算子映射以及注册的问题

### ISSUE THREAD

**Issue by flora077** [ThomasVonWu/SparseEnd2End#11]
大佬您好，我是一个新手，我想知道为什么只对DFA进行自定义算子的映射以及注册，head中还有refine或者temp_gnn等，这些不是常见的ffn或者norm算子，这些不需要进行映射和注册么？难道这些算子在pytorch的aten以及onnx中已经支持了么？

**Comment by ThomasVonWu** [comment]
ONNX自定义算子映射和注册解决痛点是:
+ ONNX 官方维护了一个标准化的算子库。如果PyTorch自定义算子没有出现在该库中，则无法直接导出。在这种情况下，需要为该算子编写一个自定义的 ONNX 操作(定义映射符号), 常见的Conv/Norm/Self-Attention/Multihead-Attention这些PyTorch的ATen 和ONNX官方都已经支持:可以查看详情: [https://github.com/ThomasVonWu/SparseEnd2End/blob/main/resources/docs/Onnx%20Operator%20Schemas.md](url)
+ 为了实现自定义功能需求, 比如说, 本仓库的多尺度多视角特征聚合操作, 需要我们自己实现一个cuda加速并行计算, 这里我们把该计算操作简称DFA算子, 为了后续的推理引擎使用的支持:ONNXRuntime 和 TensorRT,需要首先在ONNX 端做好DFA算子的符号映射, 最后在推理引擎端将具体的加速运算的实现注册到内部中, 实现最终车端和工作站的部署需求.

**Comment by flora077** [comment]
感谢您的回复，所以我理解就是在v3版本中DFA使用了cuda加速，如果是v1版本的话是否可以直接导出onnx了呢

**Comment by ThomasVonWu** [comment]
+ 其实v3版本也是也可以直接导出ONNX, 在 `head/sparse4d_blocks/core_blocks.py` 设置 self.use_deformable_func=False就可以:[使用torch.nn.functional.grid_sample替换DFA算子](https://github.com/ThomasVonWu/SparseEnd2End/blob/e1c59859583ad6a6426edb193543fa66b9067294/modules/head/sparse4d_blocks/core_blocks.py#L271C13-L271C89). 但是PyTorch由于没有做加速优化, 在RTX3090推理24G的显存都会显存爆炸. 所以没有什么使用价值.
+ DETR 我记得都是常规算子,可以直接转换ONNX即可.

**Comment by flora077** [comment]
是的 我有看到这个 我看v1的dfa中也都是常规算子组成的 所以不设置false是不是也可以直接导出onnx 只要将forward中推理无关内容删掉就可以

---- 回复的原邮件 ----
| 发件人 | Thomas Von ***@***.***> |
| 发送日期 | 2024年12月05日 16:36 |
| 收件人 | ThomasVonWu/SparseEnd2End ***@***.***> |
| 抄送人 | flora077 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ThomasVonWu/SparseEnd2End] 有关于算子映射以及注册的问题 (Issue #11) |

其实v3版本也是也可以直接导出ONNX, 在 head/sparse4d_blocks/core_blocks.py 设置 self.use_deformable_func=False就可以:使用torch.nn.functional.grid_sample替换DFA算子. 但是PyTorch由于没有做加速优化, 在RTX3090推理24G的显存都会显存爆炸. 所以没有什么使用价值.
DETR 我记得都是常规算子,可以直接转换ONNX即可.

**Comment by PonyAIjkz** [comment]
可以将推理不相关的删除, 直接导出没什么问题的

**Comment by ThomasVonWu** [comment]
可以将推理不相关的删除, 直接导出没什么问题的

**Comment by flora077** [comment]
好的！ 十分感谢您的回复 我正在尝试将其导出
