### ISSUE TITLE
有关dummy_temp_instance_feature等问题

### ISSUE THREAD

**Issue by flora077** [ThomasVonWu/SparseEnd2End#12]
作者您好，经过我的思考，本小白又出现了新的问题，实在是打扰了

- Sparse4DHead2nd有参数dummy_temp_instance_feature，我注意到您设置为了全零，用于方便导出onnx，但是在sparse4dv3模型中，这应该是通过instance_bank得到的上一帧的结果，您设置全零的话不会使onnx和pytorch的推理结果产生不同么？
- 我注意到您将head和backbone分别导出onnx，后面是通过onnx.compose将两个部分合并的么？

**Comment by ThomasVonWu** [comment]
+ temp_instance_feature 在每一帧推理过程就是个全0的常量tensor.
+ 分别导出onnx, 分别转换trt engien, 然后推理部署的过程, 将他们串联起来就可以了.

**Comment by flora077** [comment]
好的，非常感谢您的回答
