### ISSUE TITLE
部署模型推理代码问题

### ISSUE THREAD

**Issue by gaston8580** [ThomasVonWu/SparseEnd2End#13]
作者你好，我看了一下python的代码，前后两帧的衔接需要使用instance_bank来进行cache的计算和获取。那么在模型线上部署时，是否需要将instance_bank也进行onnx/trt转换以使用它内部的函数，或者是在部署代码中用C++来实现instance_bank.get(), instance_bank.cache(), instance_bank.get_track_id()这些函数呢？希望得到你的回答，感谢。

**Comment by ThomasVonWu** [comment]
instance_bank 这部分需要使用C++实现:
+ instance_bank 虽然继承了torch.nn.Module, 但是, 它并没有涉及到相关nn算子的调用和计算, 对TensorRT推理引擎的加速需求不大.
```bash
class InstanceBank(nn.Module)
```
+ 另外, instance_bank 将会缓存历史帧的信息self.cached_anchor, self.cached_feature, etc. 建议部署中用C++来实现其相关方法,直接放入engine中无法缓存历史信息并调用历史信息.

**Comment by gaston8580** [comment]
好的，明白了，非常感谢！
