### ISSUE TITLE
使用实际数据验证自定义op， 其输出和pytorch存在差异

### ISSUE THREAD

**Issue by pangxiaowen** [ThomasVonWu/SparseEnd2End#2]
![82ac086c22aefa7597aea4ab35a8879](https://github.com/user-attachments/assets/8c6936a1-fbf1-4ff3-b466-dd254d5f3b0d)
![be1eec13c0905562c47686407eab5bc](https://github.com/user-attachments/assets/fe30f91d-6517-4efb-8639-d49a5c29f61d)

如果使用随机生产的sampling_loc，则不会出现该问题。

**Comment by pangxiaowen** [comment]
不好意思，解决了。 tensor的内存不连续， 直接推理问题。

**Comment by Youngtrue** [comment]
@pangxiaowen 可以问一下具体是哪里的内存不连续会导致问题吗，谢谢
