### ISSUE TITLE
Exception: Error: Invalid box type: None

### ISSUE THREAD

**Issue by Tangme10** [ThomasVonWu/SparseEnd2End#4]
Loaded ground truth annotations for 81 samples.
Filtering tracks
Traceback (most recent call last):
  File "/home/qw/Tangme10/SparseEnd2End/script/train.py", line 140, in <module>
    main()
  File "/home/qw/Tangme10/SparseEnd2End/script/train.py", line 127, in main
    train_api(
  File "/home/qw/Tangme10/SparseEnd2End/tool/trainer/train_sdk.py", line 119, in train_api
    runner.run(data_loaders, cfg["workflow"])
  File "/home/qw/Tangme10/SparseEnd2End/tool/runner/iter_based_runner.py", line 109, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/qw/Tangme10/SparseEnd2End/tool/runner/iter_based_runner.py", line 42, in train
    self.call_hook("after_train_iter")
  File "/home/qw/Tangme10/SparseEnd2End/tool/runner/base_runner.py", line 249, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/qw/Tangme10/SparseEnd2End/tool/hook/evaluation.py", line 267, in after_train_iter
    self._do_evaluate(runner)
  File "/home/qw/Tangme10/SparseEnd2End/tool/hook/evaluation.py", line 278, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/qw/Tangme10/SparseEnd2End/tool/hook/evaluation.py", line 365, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/home/qw/Tangme10/SparseEnd2End/dataset/nuscenes_dataset.py", line 328, in evaluate
    ret_dict = self._evaluate_single(
  File "/home/qw/Tangme10/SparseEnd2End/dataset/nuscenes_dataset.py", line 498, in _evaluate_single
    nusc_eval = TrackingEval(
  File "/home/qw/anaconda3/envs/sparsee2e/lib/python3.8/site-packages/nuscenes/eval/tracking/evaluate.py", line 97, in __init__
    pred_boxes = filter_eval_boxes(nusc, pred_boxes, self.cfg.class_range, verbose=verbose)
  File "/home/qw/anaconda3/envs/sparsee2e/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 219, in filter_eval_boxes
    class_field = _get_box_class_field(eval_boxes)
  File "/home/qw/anaconda3/envs/sparsee2e/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 283, in _get_box_class_field
    raise Exception('Error: Invalid box type: %s' % box)
Exception: Error: Invalid box type: None

After deleting the logger, the model training shows the above error, can you help me with this, thanks a lot!

**Comment by ThomasVonWu** [comment]
It is very similar to the previous question. I suggest adding the --no-validate argument. For example, you can run the following command:clear && python script/train.py dataset/config/[your_config.py] --no-validate

**Comment by Tangme10** [comment]
hi Dr. Thomas，Thank you very much for your reply
Using the -no-validate command will allow the training to run without hindrance. Last week, I directly deleted it in the code for the logger problem.it is also useful
However, the problem of Invalid box type: None still appears in the test. I found that the v1.0-mini dataset uses dump_nusc_ann_json.py to generate the required .json file, which contains NaN values. I replaced it with ''0.0'', and the problem of Invalid box type: None was solved. But when I use trainval to do it, the same thing happens. At the same time, when using the trainval dataset to generate anchors by K-means, there will be a warning of no gt boxes. I don't know if this will have an impact. Recently I am going to convert the resnet code to SNN, but I don't know if I need to modify the loss function
Not sure if there is anything that I am not doing correctly. Thank you for your great work and effort in maintaining this!
Your work is very great and very useful to me, thank you for your reply, and I am looking forward to your update of the code！

------------------------------------------------------------------------------------
Some solutions for others：
1.  File "script/test.py", line 88, in main
    print(checkpoint["meta"]["CLASSES"])
KeyError: 'CLASSES'
add calsses to ckpt
import torch
checkpoint_path = "/home/qw/Tangme10/SparseEnd2End/e2e_worklog/sparse4d_temporal_r50_1x1_bs1_256x704_mini/iter_66.pth"
checkpoint = torch.load(checkpoint_path, map_location='cpu')

if 'meta' not in checkpoint:
    checkpoint['meta'] = {}

classes = ['car', 'truck','construction_vehicle','bus', 'trailer', 'barrier','motorcycle','bicycle','pedestrian', 'traffic_cone']
checkpoint['meta']['CLASSES'] = classes

torch.save(checkpoint, checkpoint_path)
print("Checkpoint updated successfully with CLASSES.")

2.data_time problem
 i just chaged the code  from textlog    
     if "time" in log_dict.keys():
                self.time_sec_tot += log_dict["time"] * self.interval
                time_sec_avg = self.time_sec_tot / (runner.iter - self.start_iter + 1)
                eta_sec = time_sec_avg * (runner.max_iters - runner.iter - 1)
                eta_str = str(datetime.timedelta(seconds=int(eta_sec)))
                log_str += f"eta: {eta_str}, "
                # log_str += (
                #     f'time: {log_dict["time"]:.3f}, '
                #     f'data_time: {log_dict["data_time"]:.3f}, '
                # )
                # statistic memory
                log_str += (
                    f'time: {log_dict.get("time", 0):.3f}, '
                    f'data_time: {log_dict.get("data_time", 0):.3f}, ')
                # if torch.cuda.is_available():
                #     log_str += f'memory: {log_dict["memory"]}, '

**Comment by ThomasVonWu** [comment]
**Q1:** When using the trainval dataset to generate anchors by K-means, there will be a warning of no gt boxes. I don't know if this will have an impact?
**A1:** I have added a `continue` statement in `dump_nusc_ann_json.py` to exit the loop. It means there's no valid gtbox in this frame. When we cluster the boxes using K-Means, we can ignore this waring. 

**Q2:**  I found that the v1.0-mini dataset uses dump_nusc_ann_json.py to generate the required .json file, which contains NaN values. I replaced it with ''0.0'', and the problem of Invalid box type: None was solved？
**A2:** I think there is no need to deal with this issue additionally. Because I've added this processing logic to the dataset script `dataset/nuscenes_dataset.py`：
```bash
if self._with_velocity:  
    gt_velocity = np.array(info["gt_velocity"]).reshape(-1, 2)[mask]
    nan_mask = np.isnan(gt_velocity[:, 0])  # 判断标注文件中的速度是否都有效
    gt_velocity[nan_mask] = [0.0, 0.0]  # 标注中速度无效设置为0
    gt_bboxes_3d = np.concatenate([gt_bboxes_3d, gt_velocity], axis=-1)
```

**Q3:** However, the problem of Invalid box type: None still appears in the test？
**A3:** I think if the training link is ok with no problem, you can directly start the NuScenes full data training(you can use config:`dataset/config/sparse4d_temporal_r50_1x4_bs22_256x704.py`) instead of NuScenes MINI. In my personal experience, when the training converges, the test doesn't have the problem of invalid box type: None.

**Q4:** Recently I am going to convert the resnet code to SNN, but I don't know if I need to modify the loss function？
**A4:** In my personal experience, you don't need to modify the loss function, you just need to train the whole model: SNN + Sparsehead start with small learning rate. If you pretriain the backbone:SNN in nuImages or ImageNet, it is easier to converge and get good trainging results.

**Comment by Tangme10** [comment]
I apologize for not getting back to you until now.thank you very much for your reply, it has been very helpful.
I have only recently started learning about SNN and am exploring this area, I didn't really understand the last piece of advice you gave and wasn't sure how to go about implementing the two methods you mentioned. Yesterday I modified the /modules/backbone/resnet.py

`class SpikingNeuron(nn.Module):
    def __init__(self, threshold=1.0, decay=0.9):
        super(SpikingNeuron, self).__init__()
        self.threshold = threshold
        self.decay = decay
        self.membrane_potential = None

    def forward(self, x):
        if self.membrane_potential is None or self.membrane_potential.shape != x.shape:
            self.membrane_potential = torch.zeros_like(x)
        self.membrane_potential = self.decay * self.membrane_potential + x
        out = (self.membrane_potential >= self.threshold).float()
        self.membrane_potential = self.membrane_potential * (1 - out)
        return out`
        

`    def forward(self, x):
        """Forward function."""

        def _inner_forward(x):
            identity = x
            
            out = self.conv1(x)
            out = self.norm1(out)
            out = self.spike_fn(out)

            out = self.conv2(out)
            out = self.norm2(out)
            out = self.spike_fn(out)

            out = self.conv3(out)
            out = self.norm3(out)

            if self.downsample is not None:
                identity = self.downsample(x)

            # Ensure the dimensions match for addition, including channels
            if out.shape != identity.shape:
                # Adjust channels if necessary
                if out.shape[1] != identity.shape[1]:
                    identity = torch.nn.Conv2d(identity.shape[1], out.shape[1], kernel_size=1, stride=1, bias=False)(identity)
                
                # Adjust spatial dimensions (H, W)
                identity = nn.functional.interpolate(identity, size=out.shape[2:], mode='nearest')

            out += identity

            return out

        if self.with_cp and x.requires_grad:
            out = cp.checkpoint(_inner_forward, x)
        else:
            out = _inner_forward(x)

        out = self.spike_fn(out)

        return out`

After I made this modification there were some problems :
RuntimeError: The size of tensor a (16896) must match the size of tensor b (264) at non-singleton dimension 0
so I had to modify the loss function

`    def loss(self, depth_preds, gt_depths):  
        loss = 0.0
        for pred, gt in zip(depth_preds, gt_depths):
            # 调整预测和真实深度的形状，以匹配相应的维度
            if pred.shape != gt.shape:
                min_shape = [min(p, g) for p, g in zip(pred.shape, gt.shape)]
                pred = pred[:, :min_shape[1], :min_shape[2], :min_shape[3]]
                gt = gt[:, :min_shape[1], :min_shape[2], :min_shape[3]]

            pred = pred.contiguous().flatten()
            gt = gt.contiguous().flatten()

            min_length = min(pred.size(0), gt.size(0))
            pred = pred[:min_length]
            gt = gt[:min_length]
            fg_mask = torch.logical_and(gt > 0.0, torch.logical_not(torch.isnan(pred)))
            gt = gt[fg_mask]
            pred = pred[fg_mask]
            pred = torch.clamp(pred, 0.0, self.max_depth)
            with autocast(enabled=False):
                error = torch.abs(pred - gt).sum()
                _loss = error / max(1.0, len(gt) * len(depth_preds)) * self.loss_weight
            loss = loss + _loss
        return loss
    `
I've found that  memory clock grows until it explodes.
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 68.00 MiB (GPU 0; 23.68 GiB total capacity; 19.18 GiB already allocated; 63.75 MiB free; 21.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF（I think it must be my own fault.）

[resnet+core_block.zip](https://github.com/user-attachments/files/17582383/resnet%2Bcore_block.zip)

Thank you for your answers Looking forward to your updates and replies!

**Comment by ThomasVonWu** [comment]
Hi, I’m sorry for the late reply. 
I haven't used SNN as an image encoder, but I found that the feature shapes extracted from the backbone have changed. From SNN, we obtain the following feature shapes:
```bash
torch.Size([6, 256, 64, 176])
torch.Size([6, 512, 4, 11])
torch.Size([6, 1024, 1, 1])
torch.Size([6, 2048, 1, 1])
```
We hope to extract features at different scales from the original images. Therefore, we use `ResNet` to downsample and achieve the following feature shapes:
```bash
xx= torch.Size([6, 256, 64, 176])
xx= torch.Size([6, 512, 32, 88])
xx= torch.Size([6, 1024, 16, 44])
xx= torch.Size([6, 2048, 8, 22])
```
I hope this information is useful for you.

**Comment by Tangme10** [comment]
非常感谢您的回复，对于SNN的修改我已经完成。但是在训练时由于我只有一张24G的3090，所以只能在batchsize=1的时候训练，感觉很容易训飞，我尝试将学习率降低到1e-6，，您觉得大概什么学习率较为合适，这个会不会太小了

**Comment by ThomasVonWu** [comment]
batchsize大点尽可能把3090的显存吃满, 学习率1e-6可以的. 如果训练崩了, 还可以再降低一个数量级. 
学习率低点只会影响训练收敛速度和收敛效果, 学习率高了可能直接导致训练发散.
当你找到一个可以让训练收敛的学习率后,可以把它慢慢大, 加速收敛速度.

**Comment by Tangme10** [comment]
非常感谢您的帮助，基本上解决了我目前的问题，感谢您的无私奉献，谢谢！
期待您后续的更新！

**Comment by jiangtguo** [comment]
你好，我有类似的问题，在执行torchpack dist-run -np 2 python tools/train.py configs/nuscenes/det/centerhead/lssfpn/camera+radar/resnet50/default.yaml时出现raise Exception('Error: Invalid box type: %s' % box)
Exception: Error: Invalid box type: None这样的错误。我按照Q2的回答修改后仍然出现错误，我使用的v1.0-mini dataset，我认为uses dump_nusc_ann_json.py to generate the required .json file将NaN变为0和Q2中的代码是一样的效果。但是我还是想知道dump_nusc_ann_json.py to generate the required .json file, which contains NaN values. I replaced it with ''0.0'', 是怎么做到的？

![Image](https://github.com/user-attachments/assets/f45e9a70-ff39-4840-9a79-5201bfe98715)我并没有找到dump_nusc_ann_json.py类似的文件

> **Q1:** When using the trainval dataset to generate anchors by K-means, there will be a warning of no gt boxes. I don't know if this will have an impact? **A1:** I have added a statement in to exit the loop. It means there's no valid gtbox in this frame. When we cluster the boxes using K-Means, we can ignore this waring.`continue``dump_nusc_ann_json.py`
> 
> **Q2:** I found that the v1.0-mini dataset uses dump_nusc_ann_json.py to generate the required .json file, which contains NaN values. I replaced it with ''0.0'', and the problem of Invalid box type: None was solved？ **A2:** I think there is no need to deal with this issue additionally. Because I've added this processing logic to the dataset script ：`dataset/nuscenes_dataset.py`
> 
> if self._with_velocity:  
>     gt_velocity = np.array(info["gt_velocity"]).reshape(-1, 2)[mask]
>     nan_mask = np.isnan(gt_velocity[:, 0])  # 判断标注文件中的速度是否都有效
>     gt_velocity[nan_mask] = [0.0, 0.0]  # 标注中速度无效设置为0
>     gt_bboxes_3d = np.concatenate([gt_bboxes_3d, gt_velocity], axis=-1)
> **Q3:** However, the problem of Invalid box type: None still appears in the test？ **A3:** I think if the training link is ok with no problem, you can directly start the NuScenes full data training(you can use config:) instead of NuScenes MINI. In my personal experience, when the training converges, the test doesn't have the problem of invalid box type: None.`dataset/config/sparse4d_temporal_r50_1x4_bs22_256x704.py`
> 
> **Q4:** Recently I am going to convert the resnet code to SNN, but I don't know if I need to modify the loss function？ **A4:** In my personal experience, you don't need to modify the loss function, you just need to train the whole model: SNN + Sparsehead start with small learning rate. If you pretriain the backbone:SNN in nuImages or ImageNet, it is easier to converge and get good trainging results.

**Comment by jiangtguo** [comment]
并且第一个epoch可以正常训练，第二个epoch的val时发生错误
