### ISSUE TITLE
params参数定义

### ISSUE THREAD

**Issue by Tangme10** [ThomasVonWu/SparseEnd2End#9]
大佬您好，
我在编译时
在onboard/preprocessor/img_preprocessor.h中的params报错
class Preprocess {
 public:
  // 显式构造函数，接受Params类型的参数
  explicit Preprocess(const Params& params); 
  
  /home/qw/Tangme10/SparseEnd2End/onboard/preprocessor/img_preprocessor.h:18:29: error: ‘Params’ does not name a type
   18 |   explicit Preprocess(const Params& params);
   
 请问此处的params定义在哪里呢，请问是需要#include "../common/parameter.h"吗，但是我尝试之后并没有效果

**Comment by Tangme10** [comment]
在/common/parameter.h中，添加了  using Params = E2EParams;类别名解决

**Comment by ThomasVonWu** [comment]
整个onboard都在开发过程中, 还没有完善好. 最近有点时间我准备把各部分串起来, 哈哈

**Comment by Tangme10** [comment]
好的，大佬，我也在试着学习onboard里面C++的东西，但是只有大一接触过c++，导致很多都是一知半解，导师让元旦前搞出来，但是进展很缓慢，我编译出来的一个main二进制文件，./main没有效果，具体应该在tensorrt.cpp/tensorrt.h增加什么还没搞明白，期待您的更新。
非常感谢您前面的帮助
